import type { Project, Task } from '@/lib/types';
import { addDays } from 'date-fns';

export const projects: Project[] = [
    {
        id: 'proj-1',
        companyId: 'company-1',
        name: 'Huddle Redesign',
        description: 'A complete redesign of the main Huddle application and marketing website.',
        status: 'active',
        createdBy: 'user-1',
        members: ['user-1', 'user-2', 'user-3', 'user-5'],
        createdAt: new Date(),
    }
]

export const tasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Design new landing page hero',
    description: 'Create 3-5 variations of the new hero section for the marketing website. Focus on clear CTA and brand message.',
    assignee: 'user-3',
    dueDate: addDays(new Date(), 2),
    status: 'in_progress',
    priority: 'high',
    tags: ['design', 'website'],
    commentsCount: 3,
    attachmentsCount: 2,
    companyId: 'company-1',
    createdAt: new Date(),
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Setup new database schema',
    description: 'Implement the new Firestore schema based on the approved backend.json document.',
    assignee: 'user-2',
    dueDate: addDays(new Date(), 3),
    status: 'in_progress',
    priority: 'high',
    tags: ['backend', 'firebase'],
    commentsCount: 8,
    attachmentsCount: 1,
    companyId: 'company-1',
    createdAt: new Date(),
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Develop dashboard components',
    description: 'Build out the main components for the new dashboard: BusinessPulse, Leaderboard, etc.',
    assignee: 'user-5',
    dueDate: addDays(new Date(), 5),
    status: 'todo',
    priority: 'medium',
    tags: ['frontend', 'react'],
    commentsCount: 0,
    attachmentsCount: 0,
    companyId: 'company-1',
    createdAt: new Date(),
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    title: 'Write copy for pricing page',
    description: 'Draft the new copy for the pricing page, focusing on value proposition for each tier.',
    assignee: 'user-1',
    dueDate: addDays(new Date(), 1),
    status: 'todo',
    priority: 'medium',
    tags: ['copywriting', 'website'],
    commentsCount: 2,
    attachmentsCount: 0,
    companyId: 'company-1',
    createdAt: new Date(),
  },
  {
    id: 'task-5',
    projectId: 'proj-1',
    title: 'Fix login page CSS bug',
    description: 'The Google Sign-In button is not properly aligned on mobile devices.',
    assignee: 'user-5',
    dueDate: addDays(new Date(), -1),
    status: 'done',
    priority: 'low',
    tags: ['bug', 'css'],
    commentsCount: 5,
    attachmentsCount: 1,
    companyId: 'company-1',
    createdAt: new Date(),
  },
  {
    id: 'task-6',
    projectId: 'proj-1',
    title: 'User testing session recruitment',
    description: 'Recruit 5-7 existing users for a paid testing session on the new designs.',
    assignee: 'user-1',
    dueDate: addDays(new Date(), 4),
    status: 'todo',
    priority: 'low',
    tags: ['user-research'],
    commentsCount: 1,
    attachmentsCount: 1,
    companyId: 'company-1',
    createdAt: new Date(),
  },
  {
    id: 'task-7',
    projectId: 'proj-1',
    title: 'Finalize Q4 roadmap',
    description: 'Review all proposals and finalize the product roadmap for the last quarter.',
    assignee: 'user-1',
    dueDate: addDays(new Date(), 7),
    status: 'done',
    priority: 'high',
    tags: ['planning', 'strategy'],
    commentsCount: 12,
    attachmentsCount: 4,
    companyId: 'company-1',
    createdAt: new Date(),
  },
];
